@startuml Context Diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include FONTAWESOME/users.puml

Person(clients, "Clientes", "Contratan y utilizan los servicios de robafone", $sprite="users")
Container(mainframe, "Marco principal", "Sistema software", "Almacena la información y datos recibidos por el sistema de contratacion de servicios")
Container(hireservices, "Sistema de contratación servicios", "Sistema software", "Permite a los usuarios contratar y gestionar los servicios disponibles, además de consultar sus facturas")
Person(employees, "Empleados", "Envían y gestionan las correspondientes facturas de los servicios", $sprite="users")

Rel(hireservices, mainframe, "Envía información sobre los servicios y facturas de los correspondientes clientes")
Rel(clients, hireservices, "Contratación y consulta de servicios, incluyendo facturas")
Rel_L(employees, hireservices, "Genera facturas")